config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :houses
  resources :house_rental_requests

  root to: "sessions#new"
end

app/models/house.rb
class House < ActiveRecord::Base
  validates :owner_id, :address, presence: true
  validates :address, uniqueness: :true

  belongs_to :owner,
    class_name: "User",
    foreign_key: :owner_id,
    primary_key: :id

  has_many :rental_requests,
    class_name: "HouseRentalRequest",
    foreign_key: :house_id,
    primary_key: :id

  has_many :renters, through: :rental_requests, source: :renter

  def belongs_to_user?(user)
    self.owner_id == user.id
  end
end

app/models/house_rental_request.rb
class HouseRentalRequest < ActiveRecord::Base
  validates :user_id, :house_id, :start_date, :end_date, presence: true

  belongs_to :house,
    class_name: "House",
    foreign_key: :house_id,
    primary_key: :id

  belongs_to :renter,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  validates :username, :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :owned_houses,
    class_name: "House",
    foreign_key: :owner_id,
    primary_key: :id

  has_many :house_rental_requests,
    class_name: "HouseRentalRequest",
    foreign_key: :user_id,
    primary_key: :id

  has_many :rented_houses, through: :house_rental_requests, source: :house

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user && @user.valid_password?(password)
    @user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def sign_in(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def sign_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def signed_in?
    !!current_user
  end

  private

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/house_rental_requests_controller.rb
class HouseRentalRequestsController < ApplicationController

  before_action :require_signed_in

  def create
    @request = HouseRentalRequest.new(rental_params)
    @request.user_id = current_user.id
    @request.status = "Pending"
    if @request.save
      flash[:errors] = ["House request Submitted!"]
      redirect_to house_url(@request.house)
    else
      flash[:errors] = @request.errors.full_messages
      render :new
    end
  end

  def new
    @request = HouseRentalRequest.new
  end

  def edit
    @request = HouseRentalRequest.find(params[:id])
  end

  def update
    @request = HouseRentalRequest.find(params[:id])
    if @request.update(rental_params)
      flash[:errors] = ["submission accepted"]
      redirect_to user_url(current_user)
    else
      flash[:errors] = ["something went awry!"]
      render :edit
    end
  end

  private

  def rental_params
    params.require(:house_rental_request).permit(:house_id, :user_id, :start_date, :end_date, :status)
  end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  before_action :require_signed_in

  def new
    @house = current_user.owned_houses.new
  end

  def create
    @house = current_user.owned_houses.new(house_params)
    if @house.save
      redirect_to house_url(@house)
    else
      flash[:errors] = @house.errors.full_messages
      render :new
    end
  end

  def show
    @house = House.find(params[:id])
    render :show
  end

  def index
    render :index
  end

  def edit
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    if @house.update(house_params)
      redirect_to house_url(@house)
    else
      flash[:errors] = @house.errors.full_messages
      render :edit
    end
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    flash[:errors] = ["House successfully deleted"]
    redirect_to houses_url
  end

  private

  def house_params
    params.require(:house).permit(:owner_id, :description, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(
              params[:session][:username],
              params[:session][:password]
              )
    if @user
      sign_in(@user)
      redirect_to houses_url
    else
      flash[:errors] = ["Invalid name or password"]
      render :new
    end
  end

  def new
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to houses_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    render :index
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_auth_token
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/views/house_rental_request/new.html.erb
<h1> Request House Rental for <%= @request.house.add %></h1>

<form action="<%=house_rental_requests_url%>" method="post">
  <%= form_auth_token %>
  <label for="start_date">Start Date:</label>
  <input id="start_date" type="date" name="house_rental_request[start_date]" value="<%= @request.start_date %>">
  <br>
  <label for="end_date">Start Date:</label>
  <input id="end_date" type="date" name="house_rental_request[end_date]" value="<%= @request.end_date %>">
  <br>
  <button>Request House</button>
</form>
<a href="<%= houses_url %>">Back to Houses Index</a>

app/views/house_rental_requests/new.html.erb
<h1> Request House Rental for <%= @request.house.address %></h1>

<form action="<%=house_rental_requests_url%>" method="post">
  <%= form_auth_token %>
  <label for="start_date">Start Date:</label>
  <input id="start_date" type="date" name="house_rental_request[start_date]" value="<%= @request.start_date %>">
  <br>
  <label for="end_date">Start Date:</label>
  <input id="end_date" type="date" name="house_rental_request[end_date]" value="<%= @request.end_date %>">
  <input type="hidden" name="house_rental_request[house_id]" value="<%= params["house_rental_request"]["house_id"]%>">
  <br>
  <button>Request House</button>
</form>
<a href="<%= houses_url %>">Back to Houses Index</a>

app/views/houses/edit.html.erb
<h1> List Your House for Rent </h1>

<form action="<%= house_url(@house) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= form_auth_token %>
  <label for="address">Address:</label>
  <input id="address" type="text" name="house[address]" value="<%= @house.address %>">
  <br>
  <label for="description">Description:</label>
  <textarea id="description" name="house[description]" value="<%= @house.description %>"></textarea>
  <br>
  <button>Update House</button>
</form>
<a href="<%= houses_url %>">Back to Houses Index</a>

app/views/houses/index.html.erb
<h1> All houses currently for rent </h1>
<% House.all.each do |house| %>
  <a href="<%= house_url(house) %>"><%= house.address %></a>
  <br>
<% end %>


<br>

<h2><a href="<%= new_house_url %>">List your own house for rent!</a></h2>

app/views/houses/new.html.erb
<h1> List Your House for Rent </h1>

<form action="<%=houses_url%>" method="post">
  <%= form_auth_token %>
  <label for="address">Address:</label>
  <input id="address" type="text" name="house[address]" value="<%= @house.address %>">
  <br>
  <label for="description">Description:</label>
  <textarea id="description" name="house[description]" value="<%= @house.description %>"></textarea>
  <br>
  <button>List Your House</button>
</form>
<a href="<%= houses_url %>">Back to Houses Index</a>

app/views/houses/show.html.erb
<h1> <%= @house.address %> </h1>
<p> Description: <%= @house.description %> </p>
<p> Owned by: <%= @house.owner.username %> </p>
<br>

<% if @house.belongs_to_user?(current_user) %>
  <a href="<%= edit_house_url(@house) %>">Edit House</a>
  <br>
<% else %>
  <form action="<%=house_rental_requests_url%>" method="post">
    <%= form_auth_token %>
    <input type="hidden" name="house_rental_request[house_id]" value="<%= @house.id %>">
    <button>Rent this house!</button>
  </form>
<% end %>

<a href="<%= houses_url %>">Back to Houses Index</a>

app/views/layouts/_auth_buttons.html.erb
<% if signed_in? %>
  <form action="<%= session_url %>" method="post">
    <%= form_auth_token %>
    <input type="hidden" name="_method" value="delete">
    <button>Sign Out</button>
  </form>
  <a href="<%= user_url(current_user)%>"> Your Profile </a>
<% else %>
<form action="<%= new_session_url %>" method="get">
  <%= form_auth_token %>
  <button>Sign In</button>
</form>
<% end %>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SandDollar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a href="http://www.sanddollaronline.com/"><img src="http://www.sanddollaronline.com/new-img/header.jpg"/></a>
  <br>
  <a href="http://www.sanddollaronline.com/"> Visit the Real Sand Dollar Site Here</a>
  <br>
  <%= render "layouts/auth_buttons" %>
  <%= render "layouts/errors" %>
  <%= yield %>

</body>
</html>

app/views/users/_approve_buttons.html.erb
<% if request.status == "Pending" %>
<form action="<%=house_rental_request_url(request)%>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="house_rental_request[status]" value="Approved">
  <button>Approve</button>
</form>
<form action="<%=house_rental_request_url(request)%>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="house_rental_request[status]" value="Denied">
  <button>Deny</button>
</form>
<% else %>
<p> <%= request.status %> </p>
<% end %>

app/views/users/new.html.erb
<h1> Create New User </h1>

<form action="<%=users_url%>" method="post">
  <%= form_auth_token %>
  <label for="username">Username:</label>
  <input id="username" type="text" name="user[username]" value="<%= @user.username %>">
  <br>
  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]" value="<%= @user.email %>">
  <br>
  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">

  <button>Sign Up</button>
</form>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>
<p> Your Rental Requests: </p>
<ul>
  <% @user.house_rental_requests.each do |request| %>
    <li><a href="<%=house_url(request.house)%>"><%= request.house.address %></a> from <%= request.start_date %> to <%= request.end_date %> <%= request.status %></li>
  <% end %>
</ul>
<br>
<p> Your Owned Houses </p>
<ul>
  <% @user.owned_houses.each do |house| %>
    <li><a href="<%=house_url(house)%>"><%= house.address %></a> </li>
      <ul>
        <% house.rental_requests.each do |request| %>
          <li> <%= request.start_date %> to <%= request.end_date %> <%= render "approve_buttons", request: request%></li>
        <% end %>
      </ul>
  <% end %>
</ul>
<br>
<a href="<%= houses_url %>">Back to Houses Index</a>